import type { Categoria } from "./clasificacion";

// Clasificación por defecto de cuentas, basada en la estructura típica de un libro
// diario tributario chileno (Balance clasificado + Estado de Resultados). Se usa
// para sugerir automáticamente la categoría al detectar una cuenta nueva por
// nombre; el usuario siempre puede reclasificarla manualmente en el Plan de Cuentas.
export const CLASIFICACION_DEFAULT: Record<string, Categoria> = {
  // --- Activos corrientes ---
  "CAJA": "EFECTIVO_EQUIVALENTE",
  "BANCO DE CHILE": "EFECTIVO_EQUIVALENTE",
  "CHIPAX WALLET": "EFECTIVO_EQUIVALENTE",
  "INVERSION EN FONDOS MUTUOS": "EFECTIVO_EQUIVALENTE",

  "ANTICIPO REMUNERACIONES": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "ANTICIPO DE PROVEEDORES": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "IVA CREDITO FISCAL": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "GARANTIAS": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "REMANENTE CREDITO FISCAL": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTO POR RECUPERAR": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "IVA ANTICIPADO": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "PAGOS PROVISIONAL MENSUAL": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "OTROS GASTOS PAGADOS POR ANTICIPADO": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",

  "CLIENTES": "DEUDORES_COMERCIALES",
  "CLIENTES CON BOLETAS": "DEUDORES_COMERCIALES",

  "EXISTENCIAS": "INVENTARIOS_CORRIENTES",

  // --- Activos no corrientes ---
  "MUEBLES Y UTILES": "PROPIEDADES_PLANTA_EQUIPO",
  "DEP ACUM ACTIVOS FIJOS": "PROPIEDADES_PLANTA_EQUIPO",
  "MAQUINARIA": "PROPIEDADES_PLANTA_EQUIPO",
  "EQUIPOS COMPUTACIONALES": "PROPIEDADES_PLANTA_EQUIPO",
  "CONSTRUCCIONES OBRAS INFRAESTRUCT": "PROPIEDADES_PLANTA_EQUIPO",

  // --- Pasivos corrientes ---
  "PRESTAMO FOGAPE": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "TARJETA DE CREDITO": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "TARJETA DE CREDITO USD": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "IVA DEBITO FISCAL": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",

  "CUENTA POR PAGAR  BEASTY FOOD": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR BEASTY FOOD": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CTA CTE POR PAGAR GRUPO RUMIANTE": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR ALMIRA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR IGNACIO SAAVEDRA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERMAIPO": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR NICOLAS DE LA FUENTE": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR PABLO ASTORGA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR MARIA INES VIAL": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERSIONES SAN MARTIN": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR FELIPE ORUETA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERSIONES LA VEGA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERSIONES CAMINO REAL": "CUENTAS_POR_PAGAR_RELACIONADAS",

  "REMUNERACIONES POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "HONORARIOS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "PROVEEDORES NACIONALES": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "FINIQUITOS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "PROPINAS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTO RETENCION 2DA CATEGORIA": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTO UNICO TRABAJADORES": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPOSICIONES POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTOS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IVA POSTERGADO": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "CUENTAS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",

  // --- Patrimonio ---
  "CAPITAL": "CAPITAL_EMITIDO",
  "RETIROS": "CAPITAL_EMITIDO",
  "RESULTADO ACUMULADO": "GANANCIAS_PERDIDAS_ACUMULADAS",
  "PERDIDAS ACUMULADAS": "GANANCIAS_PERDIDAS_ACUMULADAS",

  // --- Estado de Resultados ---
  "VENTAS": "INGRESOS",
  "VENTAS CON BOLETAS": "INGRESOS",
  "INGRESOS POR ACTIVIDADES ORDINARIAS": "INGRESOS",

  "COSTO DE VENTAS": "COSTO_VENTAS",

  "SUELDO": "GASTOS_ADMIN_VENTAS",
  "GRATIFICACION": "GASTOS_ADMIN_VENTAS",
  "HORAS EXTRAS": "GASTOS_ADMIN_VENTAS",
  "MOVILIZACION Y COLACION": "GASTOS_ADMIN_VENTAS",
  "FERIADO LEGAL": "GASTOS_ADMIN_VENTAS",
  "BONOS": "GASTOS_ADMIN_VENTAS",
  "APORTE PATRONAL": "GASTOS_ADMIN_VENTAS",
  "INDEMNIZACIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS CONTABLES": "GASTOS_ADMIN_VENTAS",
  "ARTICULOS Y UTILES DE ASEO": "GASTOS_ADMIN_VENTAS",
  "PATENTE COMERCIAL": "GASTOS_ADMIN_VENTAS",
  "MARKETING": "GASTOS_ADMIN_VENTAS",
  "REPARACIONES Y MANTENCIONES": "GASTOS_ADMIN_VENTAS",
  "GASTOS LEGALES Y NOTARIALES": "GASTOS_ADMIN_VENTAS",
  "SEGUROS OFICINA": "GASTOS_ADMIN_VENTAS",
  "CUENTAS / UTILITIES / GGCC": "GASTOS_ADMIN_VENTAS",
  "GASTOS ADMINISTRACION": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS": "GASTOS_ADMIN_VENTAS",
  "ARRIENDOS": "GASTOS_ADMIN_VENTAS",
  "TRANSPORTE Y ENCOMIENDAS": "GASTOS_ADMIN_VENTAS",
  "GASTOS GENERALES": "GASTOS_ADMIN_VENTAS",
  "UNIFORMES": "GASTOS_ADMIN_VENTAS",
  "GESTION DE PERSONAL": "GASTOS_ADMIN_VENTAS",
  "OTROS GASTOS VARIABLES": "GASTOS_ADMIN_VENTAS",
  "PACKAGING Y PAPELERIA": "GASTOS_ADMIN_VENTAS",
  "SISTEMAS Y COMUNICACIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR SERVICIO": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR COCINA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR MARKETING": "GASTOS_ADMIN_VENTAS",
  "COMISIONES PASARELAS": "GASTOS_ADMIN_VENTAS",
  "HOSTING": "GASTOS_ADMIN_VENTAS",
  "ASESORIAS ESTRATEGICAS": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR CAJA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS ANFITRIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS BARRA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS COPERIA": "GASTOS_ADMIN_VENTAS",
  "DIFERENCIA DE CAMBIO PERDIDA": "GASTOS_ADMIN_VENTAS",
  "DIFERENCIA DE CAMBIO GANANCIAS": "GASTOS_ADMIN_VENTAS",
  "GASTOS BANCARIOS": "GASTOS_ADMIN_VENTAS",

  "DEPRECIACION DEL EJERCICIO": "COSTOS_FINANCIEROS",
  "INGRESOS FINANCIEROS": "COSTOS_FINANCIEROS",
  "RESULTADOS POR UNIDADES DE REAJUSTE": "COSTOS_FINANCIEROS",

  "REAJUSTES GANADOS": "OTRAS_GANANCIAS_PERDIDAS",
  "REAJUSTE REMANENTE IVA": "OTRAS_GANANCIAS_PERDIDAS",
  "GANANCIAS (PERDIDAS) DE CAMBIO EN MONEDA EXTRANJERA": "OTRAS_GANANCIAS_PERDIDAS",

  "IMPUESTO A LAS GANANCIAS": "IMPUESTO_GANANCIAS",
};

function normalizarNombre(nombre: string) {
  return nombre
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // quita tildes
    .trim()
    .toUpperCase()
    .replace(/\s+/g, " ");
}

const CLASIFICACION_NORMALIZADA: Record<string, Categoria> = Object.fromEntries(
  Object.entries(CLASIFICACION_DEFAULT).map(([nombre, categoria]) => [normalizarNombre(nombre), categoria])
);

export function sugerirCategoria(nombreCuenta: string): Categoria {
  return CLASIFICACION_NORMALIZADA[normalizarNombre(nombreCuenta)] ?? "SIN_CLASIFICAR";
}
