import type { SeccionPL } from "./pl-secciones";

// Clasificación por defecto de cuentas de resultado, basada en la estructura típica
// de Estado de Resultados de un libro diario tributario chileno. Se usa para sugerir
// automáticamente la sección de P&L al detectar una cuenta nueva por nombre; el usuario
// siempre puede reclasificarla manualmente en el Plan de Cuentas.
export const CLASIFICACION_DEFAULT: Record<string, SeccionPL> = {
  "VENTAS": "INGRESOS",
  "VENTAS CON BOLETAS": "INGRESOS",
  "INGRESOS POR ACTIVIDADES ORDINARIAS": "INGRESOS",

  "COSTO DE VENTAS": "COSTO_VENTAS",

  "SUELDO": "GASTOS_ADMIN_VENTAS",
  "GRATIFICACION": "GASTOS_ADMIN_VENTAS",
  "HORAS EXTRAS": "GASTOS_ADMIN_VENTAS",
  "MOVILIZACION Y COLACION": "GASTOS_ADMIN_VENTAS",
  "FERIADO LEGAL": "GASTOS_ADMIN_VENTAS",
  "BONOS": "GASTOS_ADMIN_VENTAS",
  "APORTE PATRONAL": "GASTOS_ADMIN_VENTAS",
  "INDEMNIZACIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS CONTABLES": "GASTOS_ADMIN_VENTAS",
  "ARTICULOS Y UTILES DE ASEO": "GASTOS_ADMIN_VENTAS",
  "PATENTE COMERCIAL": "GASTOS_ADMIN_VENTAS",
  "MARKETING": "GASTOS_ADMIN_VENTAS",
  "REPARACIONES Y MANTENCIONES": "GASTOS_ADMIN_VENTAS",
  "GASTOS LEGALES Y NOTARIALES": "GASTOS_ADMIN_VENTAS",
  "SEGUROS OFICINA": "GASTOS_ADMIN_VENTAS",
  "CUENTAS / UTILITIES / GGCC": "GASTOS_ADMIN_VENTAS",
  "GASTOS ADMINISTRACION": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS": "GASTOS_ADMIN_VENTAS",
  "ARRIENDOS": "GASTOS_ADMIN_VENTAS",
  "TRANSPORTE Y ENCOMIENDAS": "GASTOS_ADMIN_VENTAS",
  "GASTOS GENERALES": "GASTOS_ADMIN_VENTAS",
  "UNIFORMES": "GASTOS_ADMIN_VENTAS",
  "GESTION DE PERSONAL": "GASTOS_ADMIN_VENTAS",
  "OTROS GASTOS VARIABLES": "GASTOS_ADMIN_VENTAS",
  "PACKAGING Y PAPELERIA": "GASTOS_ADMIN_VENTAS",
  "SISTEMAS Y COMUNICACIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR SERVICIO": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR COCINA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR MARKETING": "GASTOS_ADMIN_VENTAS",
  "COMISIONES PASARELAS": "GASTOS_ADMIN_VENTAS",
  "HOSTING": "GASTOS_ADMIN_VENTAS",
  "ASESORIAS ESTRATEGICAS": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR CAJA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS ANFITRIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS BARRA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS COPERIA": "GASTOS_ADMIN_VENTAS",
  "DIFERENCIA DE CAMBIO PERDIDA": "GASTOS_ADMIN_VENTAS",
  "DIFERENCIA DE CAMBIO GANANCIAS": "GASTOS_ADMIN_VENTAS",
  "GASTOS BANCARIOS": "GASTOS_ADMIN_VENTAS",

  "DEPRECIACION DEL EJERCICIO": "COSTOS_FINANCIEROS",
  "INGRESOS FINANCIEROS": "COSTOS_FINANCIEROS",
  "RESULTADOS POR UNIDADES DE REAJUSTE": "COSTOS_FINANCIEROS",

  "REAJUSTES GANADOS": "OTRAS_GANANCIAS_PERDIDAS",
  "REAJUSTE REMANENTE IVA": "OTRAS_GANANCIAS_PERDIDAS",
  "GANANCIAS (PERDIDAS) DE CAMBIO EN MONEDA EXTRANJERA": "OTRAS_GANANCIAS_PERDIDAS",

  "IMPUESTO A LAS GANANCIAS": "IMPUESTO_GANANCIAS",
};

function normalizarNombre(nombre: string) {
  return nombre
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // quita tildes
    .trim()
    .toUpperCase()
    .replace(/\s+/g, " ");
}

const CLASIFICACION_NORMALIZADA: Record<string, SeccionPL> = Object.fromEntries(
  Object.entries(CLASIFICACION_DEFAULT).map(([nombre, seccion]) => [normalizarNombre(nombre), seccion])
);

export function sugerirSeccionPL(nombreCuenta: string): SeccionPL {
  return CLASIFICACION_NORMALIZADA[normalizarNombre(nombreCuenta)] ?? "NONE";
}
