import { CATEGORIA_META, type Categoria, type Grupo } from "./clasificacion";

// Clasificación por defecto de cuentas, basada en la estructura típica de un libro
// diario tributario chileno (Balance clasificado + Estado de Resultados). Se usa
// para sugerir automáticamente la categoría al detectar una cuenta nueva; el
// usuario siempre puede reclasificarla manualmente en el Plan de Cuentas.
export const CLASIFICACION_DEFAULT: Record<string, Categoria> = {
  // --- Activos corrientes ---
  "CAJA": "EFECTIVO_EQUIVALENTE",
  "BANCO DE CHILE": "EFECTIVO_EQUIVALENTE",
  "CHIPAX WALLET": "EFECTIVO_EQUIVALENTE",
  "INVERSION EN FONDOS MUTUOS": "EFECTIVO_EQUIVALENTE",

  "ANTICIPO REMUNERACIONES": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "ANTICIPO DE PROVEEDORES": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "IVA CREDITO FISCAL": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "GARANTIAS": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "REMANENTE CREDITO FISCAL": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTO POR RECUPERAR": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "IVA ANTICIPADO": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "PAGOS PROVISIONAL MENSUAL": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "OTROS GASTOS PAGADOS POR ANTICIPADO": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",

  "CLIENTES": "DEUDORES_COMERCIALES",
  "CLIENTES CON BOLETAS": "DEUDORES_COMERCIALES",

  "EXISTENCIAS": "INVENTARIOS_CORRIENTES",

  // --- Activos no corrientes ---
  "MUEBLES Y UTILES": "PROPIEDADES_PLANTA_EQUIPO",
  "DEP ACUM ACTIVOS FIJOS": "PROPIEDADES_PLANTA_EQUIPO",
  "MAQUINARIA": "PROPIEDADES_PLANTA_EQUIPO",
  "EQUIPOS COMPUTACIONALES": "PROPIEDADES_PLANTA_EQUIPO",
  "CONSTRUCCIONES OBRAS INFRAESTRUCT": "PROPIEDADES_PLANTA_EQUIPO",

  // --- Pasivos corrientes ---
  "PRESTAMO FOGAPE": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "TARJETA DE CREDITO": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "TARJETA DE CREDITO USD": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "IVA DEBITO FISCAL": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",

  "CUENTA POR PAGAR  BEASTY FOOD": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR BEASTY FOOD": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CTA CTE POR PAGAR GRUPO RUMIANTE": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR ALMIRA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR IGNACIO SAAVEDRA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERMAIPO": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR NICOLAS DE LA FUENTE": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR PABLO ASTORGA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR MARIA INES VIAL": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERSIONES SAN MARTIN": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR FELIPE ORUETA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERSIONES LA VEGA": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "CUENTA POR PAGAR INVERSIONES CAMINO REAL": "CUENTAS_POR_PAGAR_RELACIONADAS",

  "REMUNERACIONES POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "HONORARIOS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "PROVEEDORES NACIONALES": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "FINIQUITOS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "PROPINAS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTO RETENCION 2DA CATEGORIA": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTO UNICO TRABAJADORES": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPOSICIONES POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IMPUESTOS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "IVA POSTERGADO": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "CUENTAS POR PAGAR": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",

  // --- Patrimonio ---
  "CAPITAL": "CAPITAL_EMITIDO",
  "RETIROS": "CAPITAL_EMITIDO",
  "RESULTADO ACUMULADO": "GANANCIAS_PERDIDAS_ACUMULADAS",
  "PERDIDAS ACUMULADAS": "GANANCIAS_PERDIDAS_ACUMULADAS",

  // --- Estado de Resultados ---
  "VENTAS": "INGRESOS",
  "VENTAS CON BOLETAS": "INGRESOS",
  "INGRESOS POR ACTIVIDADES ORDINARIAS": "INGRESOS",

  "COSTO DE VENTAS": "COSTO_VENTAS",

  "SUELDO": "GASTOS_ADMIN_VENTAS",
  "GRATIFICACION": "GASTOS_ADMIN_VENTAS",
  "HORAS EXTRAS": "GASTOS_ADMIN_VENTAS",
  "MOVILIZACION Y COLACION": "GASTOS_ADMIN_VENTAS",
  "FERIADO LEGAL": "GASTOS_ADMIN_VENTAS",
  "BONOS": "GASTOS_ADMIN_VENTAS",
  "APORTE PATRONAL": "GASTOS_ADMIN_VENTAS",
  "INDEMNIZACIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS CONTABLES": "GASTOS_ADMIN_VENTAS",
  "ARTICULOS Y UTILES DE ASEO": "GASTOS_ADMIN_VENTAS",
  "PATENTE COMERCIAL": "GASTOS_ADMIN_VENTAS",
  "MARKETING": "GASTOS_ADMIN_VENTAS",
  "REPARACIONES Y MANTENCIONES": "GASTOS_ADMIN_VENTAS",
  "GASTOS LEGALES Y NOTARIALES": "GASTOS_ADMIN_VENTAS",
  "SEGUROS OFICINA": "GASTOS_ADMIN_VENTAS",
  "CUENTAS / UTILITIES / GGCC": "GASTOS_ADMIN_VENTAS",
  "GASTOS ADMINISTRACION": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS": "GASTOS_ADMIN_VENTAS",
  "ARRIENDOS": "GASTOS_ADMIN_VENTAS",
  "TRANSPORTE Y ENCOMIENDAS": "GASTOS_ADMIN_VENTAS",
  "GASTOS GENERALES": "GASTOS_ADMIN_VENTAS",
  "UNIFORMES": "GASTOS_ADMIN_VENTAS",
  "GESTION DE PERSONAL": "GASTOS_ADMIN_VENTAS",
  "OTROS GASTOS VARIABLES": "GASTOS_ADMIN_VENTAS",
  "PACKAGING Y PAPELERIA": "GASTOS_ADMIN_VENTAS",
  "SISTEMAS Y COMUNICACIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR SERVICIO": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR COCINA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR MARKETING": "GASTOS_ADMIN_VENTAS",
  "COMISIONES PASARELAS": "GASTOS_ADMIN_VENTAS",
  "HOSTING": "GASTOS_ADMIN_VENTAS",
  "ASESORIAS ESTRATEGICAS": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS POR CAJA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS ANFITRIONES": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS BARRA": "GASTOS_ADMIN_VENTAS",
  "HONORARIOS COPERIA": "GASTOS_ADMIN_VENTAS",
  "DIFERENCIA DE CAMBIO PERDIDA": "GASTOS_ADMIN_VENTAS",
  "DIFERENCIA DE CAMBIO GANANCIAS": "GASTOS_ADMIN_VENTAS",
  "GASTOS BANCARIOS": "GASTOS_ADMIN_VENTAS",

  "DEPRECIACION DEL EJERCICIO": "COSTOS_FINANCIEROS",
  "INGRESOS FINANCIEROS": "COSTOS_FINANCIEROS",
  "RESULTADOS POR UNIDADES DE REAJUSTE": "COSTOS_FINANCIEROS",

  "REAJUSTES GANADOS": "OTRAS_GANANCIAS_PERDIDAS",
  "REAJUSTE REMANENTE IVA": "OTRAS_GANANCIAS_PERDIDAS",
  "GANANCIAS (PERDIDAS) DE CAMBIO EN MONEDA EXTRANJERA": "OTRAS_GANANCIAS_PERDIDAS",

  "IMPUESTO A LAS GANANCIAS": "IMPUESTO_GANANCIAS",
};

function normalizarNombre(nombre: string) {
  return nombre
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // quita tildes
    .trim()
    .toUpperCase()
    .replace(/\s+/g, " ");
}

const CLASIFICACION_NORMALIZADA: Record<string, Categoria> = Object.fromEntries(
  Object.entries(CLASIFICACION_DEFAULT).map(([nombre, categoria]) => [normalizarNombre(nombre), categoria])
);

// Grupo "amplio" (Activo/Pasivo/Patrimonio/Resultado) de cada categoría, y del
// primer dígito de un código de cuenta — el plan de cuentas chileno que exportan
// iContador y software similar es consistente entre empresas: 1xxxxx = Activo,
// 2xxxxx = Pasivo, 3xxxxx = Patrimonio, 4xxxxx/5xxxxx = Resultado. Se usa para
// evitar que una palabra clave "se escape" a la categoría equivocada — por
// ejemplo, "GASTOS VARIOS VEHÍCULOS" (código 402xxx, un gasto) no debe
// clasificarse como Propiedades, planta y equipo solo porque menciona
// "vehículo".
type GrupoAmplio = "ACTIVO" | "PASIVO" | "PATRIMONIO" | "RESULTADO";

function grupoAmplio(grupo: Grupo): GrupoAmplio {
  if (grupo === "ACTIVO_CORRIENTE" || grupo === "ACTIVO_NO_CORRIENTE") return "ACTIVO";
  if (grupo === "PASIVO_CORRIENTE" || grupo === "PASIVO_NO_CORRIENTE") return "PASIVO";
  if (grupo === "PATRIMONIO") return "PATRIMONIO";
  return "RESULTADO";
}

const GRUPO_AMPLIO_POR_PRIMER_DIGITO: Record<string, GrupoAmplio> = {
  "1": "ACTIVO",
  "2": "PASIVO",
  "3": "PATRIMONIO",
  "4": "RESULTADO",
  "5": "RESULTADO",
};

// Reglas por palabra clave: se evalúan en orden y se usa la primera que calce,
// restringida al grupo amplio que sugiere el código de cuenta (si se conoce).
const REGLAS_PALABRA_CLAVE: [RegExp, Categoria][] = [
  [/^(CAJA( CHICA)?|BANCOS?( .*)?|.*WALLET|INVERSION EN FONDOS? MUTUOS?|DIVISAS?)$/, "EFECTIVO_EQUIVALENTE"],
  [/\bANTICIPO DE CLIENTES?\b/, "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES"],
  [
    /\bIVA (CREDITO|CRED)\b|^REMANENTE.*IVA\b|\bPPM\b|PAGOS? PROVISIONAL|\bANTICIPO\b|\bPRESTAMOS? AL PERSONAL\b|IMPUESTO POR RECUPERAR|GASTOS? PAGADOS? POR ANTICIPADO/,
    "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  ],
  [/\bCLIENTES?\b|DEUDORES|CUENTAS? POR COBRAR(?!.*RELACIONAD)/, "DEUDORES_COMERCIALES"],
  [/CUENTAS? POR COBRAR.*RELACIONAD|POR COBRAR.*(SOCIO|ACCIONISTA|EMPRESA RELACIONADA)/, "CUENTAS_POR_COBRAR_RELACIONADAS"],
  [/EXISTENCIA|INVENTARIO|MERCADERIA/, "INVENTARIOS_CORRIENTES"],
  [/GARANT[IÍ]A/, "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES"],
  [
    /MUEBLES|MAQUINARIA|EQUIPOS? COMPUTACIONAL|VEHICULO|CONSTRUCCION|ACTIVO FIJO|SOFTWARE|DERECHOS? \w+|DEP\.? ?ACUM/,
    "PROPIEDADES_PLANTA_EQUIPO",
  ],
  [/TARJETA DE CREDITO|\bLEASING\b|IVA D[EÉ]BITO/, "OTROS_PASIVOS_FINANCIEROS_CORRIENTES"],
  [/CUENTA.*POR PAGAR.*RELACIONAD|CTA\.? ?CTE\.? (POR PAGAR|INVERSIONES)|^MUTUO\b|\bMUTUO\b/, "CUENTAS_POR_PAGAR_RELACIONADAS"],
  [
    /PROVEEDOR|HONORARIOS POR PAGAR|REMUNERACION|SUELDO.*PAGAR|FINIQUITOS? POR PAGAR|PROPINA|IMPUESTO|IVA POSTERGADO|IMPOSICION|PREVISION|RETENCION|CUENTAS? POR PAGAR/,
    "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  ],
  [/\bCAPITAL\b|\bRETIROS?\b/, "CAPITAL_EMITIDO"],
  [/RESULTADO ACUMULADO|P[EÉ]RDIDAS? ACUMULADAS?|UTILIDADES? ACUMULADAS?/, "GANANCIAS_PERDIDAS_ACUMULADAS"],
  [/\bVENTAS?\b|INGRESOS? POR/, "INGRESOS"],
  [/COSTO DE VENTAS?|DETERGENTE|INSUMOS Y MATERIALES|MANTENIMIENTO A EQUIPOS/, "COSTO_VENTAS"],
  [/DIFERENCIA DE CAMBIO|REAJUSTES?/, "OTRAS_GANANCIAS_PERDIDAS"],
  [/GASTOS? BANCARIOS?|COMISIONES? TRANSBANK|MULTAS? E? ?INTERESES/, "COSTOS_FINANCIEROS"],
  [/IMPUESTO A LAS GANANCIAS|IMPUESTO RENTA/, "IMPUESTO_GANANCIAS"],
  [
    /SUELDO|GRATIFICACION|HORAS EXTRAS|MOVILIZACION|COLACION|BONOS?|APORTE PATRONAL|INDEMNIZACION|HONORARIOS|ARTICULOS|PATENTE|MARKETING|REPARACION|MANTENCION|LEGALES|NOTARIAL|SEGUROS?|ARRIENDO|GASTOS?|PACKAGING|UNIFORMES?|COMISION|TELEFON|INTERNET|LUZ,? ?AGUA|COMBUSTIBLE|PUBLICIDAD|PEAJES|SUSCRIPCION|FOTOCOPIADO|SISTEMA|SOFTWARE|PLATAFORMA|TRANSPORTE|ENCOMIENDA/,
    "GASTOS_ADMIN_VENTAS",
  ],
];

// Última red de seguridad: clasificar solo por el prefijo de 3 dígitos del
// código de cuenta, cuando ni el nombre exacto ni ninguna palabra clave calzó.
const CATEGORIA_POR_PREFIJO_CODIGO: Record<string, Categoria> = {
  "101": "EFECTIVO_EQUIVALENTE",
  "102": "EFECTIVO_EQUIVALENTE",
  "103": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "104": "DEUDORES_COMERCIALES",
  "108": "DEUDORES_COMERCIALES",
  "109": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "111": "OTROS_ACTIVOS_NO_FINANCIEROS_CORRIENTES",
  "115": "PROPIEDADES_PLANTA_EQUIPO",
  "116": "PROPIEDADES_PLANTA_EQUIPO",
  "117": "OTROS_ACTIVOS_NO_CORRIENTES",
  "202": "OTROS_PASIVOS_FINANCIEROS_CORRIENTES",
  "203": "CUENTAS_POR_PAGAR_RELACIONADAS",
  "207": "OTROS_PASIVOS_NO_FINANCIEROS_CORRIENTES",
  "301": "CAPITAL_EMITIDO",
  "303": "GANANCIAS_PERDIDAS_ACUMULADAS",
  "401": "COSTO_VENTAS",
  "402": "GASTOS_ADMIN_VENTAS",
  "403": "OTRAS_GANANCIAS_PERDIDAS",
  "404": "GASTOS_ADMIN_VENTAS",
  "405": "COSTOS_FINANCIEROS",
  "408": "GASTOS_ADMIN_VENTAS",
  "501": "INGRESOS",
  "502": "OTRAS_GANANCIAS_PERDIDAS",
  "503": "OTRAS_GANANCIAS_PERDIDAS",
};

export function sugerirCategoria(nombreCuenta: string, codigoCuenta?: string | null): Categoria {
  const nombreNormalizado = normalizarNombre(nombreCuenta);

  const exacta = CLASIFICACION_NORMALIZADA[nombreNormalizado];
  if (exacta) return exacta;

  const primerDigito = codigoCuenta?.trim()?.[0];
  const grupoEsperado = primerDigito ? GRUPO_AMPLIO_POR_PRIMER_DIGITO[primerDigito] : undefined;

  for (const [patron, categoria] of REGLAS_PALABRA_CLAVE) {
    if (!patron.test(nombreNormalizado)) continue;
    if (grupoEsperado && grupoAmplio(CATEGORIA_META[categoria].grupo) !== grupoEsperado) continue;
    return categoria;
  }

  const prefijo = codigoCuenta?.trim()?.slice(0, 3);
  if (prefijo && CATEGORIA_POR_PREFIJO_CODIGO[prefijo]) {
    return CATEGORIA_POR_PREFIJO_CODIGO[prefijo];
  }

  return "SIN_CLASIFICAR";
}
